### ISSUE TITLE
Extras list

### ISSUE THREAD

**Issue by tsa-dom** [lumawelhot/Luma-varaukset#133]
Listassa voisi olla mahdollisuus mahdollisuus muokata olemassa olevien extrojen tietoja. Nyt käyttäjä joutuu poistamaan ja luomaan uudelleen extran jos haluaa muokata yksittäistä kohtaa niissä. Lisäksi lisääminen ei anna herjaa jos saman niminen extra lisätään, vaan toast ilmoittaa onnistuneesta lisäyksestä, vaikka todellisesti uutta extraa ei lisätty.

![Screenshot 2021-08-06 012525](https://user-images.githubusercontent.com/73552705/128429170-eed4eb20-8a80-4847-8dbd-fa38d8212cd2.png)

**Comment by pontushed** [comment]
Lisätty validaatio samannimisille lisäpalveluille.
