### ISSUE TITLE
Visitpage extra styles

### ISSUE THREAD

**Issue by tsa-dom** [lumawelhot/Luma-varaukset#159]
Visit-page lisävalinnat tulisi näyttää tyylitetymmin.

![Screenshot 2021-08-31 003641](https://user-images.githubusercontent.com/73552705/131409018-4c3a543d-0a59-4213-9243-a7a59884bfdf.png)

**Comment by pontushed** [comment]
Lisävalinnat näkyy ul-listana samaan tapaan kuin eventPage.js:ssä
