### ISSUE TITLE
MongoMemoryServerin toiminnallisuuden tarkistus

### ISSUE THREAD

**Issue by ankaleh** [lumawelhot/Luma-varaukset#8]
Nyt ohjelma luo ilmeisesti uuden MongoMemoryServer-olion (tietokannan) joka kerta, kun ohjelman ajaa. Se tallentuu koneelle aina uudestaan. Testeissä viitataan samaan olioon/tietokantaan, eikä tätä ongelmaa ole siellä. Alla oleva koodi on lisätty kohtaan, jossa yhteys tietokantaan otetaan ja jolla voi tutkia asiaa :

 const port = await mongoServer.getPort();
 const dbPath = await mongoServer.getDbPath();
 const dbName = await mongoServer.getDbName();
 console.log('tietoja: ', port, dbName, dbPath)

**Comment by pontushed** [comment]
Poistettu
